package modelo;
// Generated 21-may-2024 9:44:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String correo;
     private String contrasenya;
     private String rol;
     private Date fechaRegistro;
     private Set noticias = new HashSet(0);
     private Set comentarios = new HashSet(0);
     private Set comentarios_1 = new HashSet(0);
     private Set valoracions = new HashSet(0);
     private Set valoracions_1 = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nombre, String correo, String contrasenya, String rol, Date fechaRegistro, Set noticias, Set comentarios, Set comentarios_1, Set valoracions, Set valoracions_1) {
       this.nombre = nombre;
       this.correo = correo;
       this.contrasenya = contrasenya;
       this.rol = rol;
       this.fechaRegistro = fechaRegistro;
       this.noticias = noticias;
       this.comentarios = comentarios;
       this.comentarios_1 = comentarios_1;
       this.valoracions = valoracions;
       this.valoracions_1 = valoracions_1;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getNoticias() {
        return this.noticias;
    }
    
    public void setNoticias(Set noticias) {
        this.noticias = noticias;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getComentarios_1() {
        return this.comentarios_1;
    }
    
    public void setComentarios_1(Set comentarios_1) {
        this.comentarios_1 = comentarios_1;
    }
    public Set getValoracions() {
        return this.valoracions;
    }
    
    public void setValoracions(Set valoracions) {
        this.valoracions = valoracions;
    }
    public Set getValoracions_1() {
        return this.valoracions_1;
    }
    
    public void setValoracions_1(Set valoracions_1) {
        this.valoracions_1 = valoracions_1;
    }




}


