package modelo;
// Generated 21-may-2024 9:44:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Valoracion generated by hbm2java
 */
public class Valoracion  implements java.io.Serializable {


     private Integer idValoracion;
     private Comentario comentario;
     private Usuario usuario;
     private Integer puntuacion;
     private Date fechaCreacion;
     private Set usuarios = new HashSet(0);

    public Valoracion() {
    }

	
    public Valoracion(Comentario comentario, Usuario usuario) {
        this.comentario = comentario;
        this.usuario = usuario;
    }
    public Valoracion(Comentario comentario, Usuario usuario, Integer puntuacion, Date fechaCreacion, Set usuarios) {
       this.comentario = comentario;
       this.usuario = usuario;
       this.puntuacion = puntuacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarios = usuarios;
    }
   
    public Integer getIdValoracion() {
        return this.idValoracion;
    }
    
    public void setIdValoracion(Integer idValoracion) {
        this.idValoracion = idValoracion;
    }
    public Comentario getComentario() {
        return this.comentario;
    }
    
    public void setComentario(Comentario comentario) {
        this.comentario = comentario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(Integer puntuacion) {
        this.puntuacion = puntuacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


